// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"DebugUtility","status":true,"description":"デバッグ画面追加","parameters":{"DebugPlayerId":"[\"35500347\"]","AlwaysShowConsole":"false"}},
{"name":"AtsumaruGetSelfInformation","status":true,"description":"RPGアツマールのプレイヤー本人の情報を取得するAPIのためのプラグインです","parameters":{"id":"1","name":"0","profile":"0","twitterId":"0","url":"0","isPremium":"0","errorMessage":"0"}}
];
